# https://taskfile.dev

version: '3'

tasks:
  default:
    silent: true  

  proto.build:
    dir: ./
    cmds:
      - protoc --go_out=. --go_opt=paths=source_relative --go-grpc_out=. --go-grpc_opt=paths=source_relative emis/**/*.proto

#/# GIT
#/# GIT
#/# GIT
  git.all:
    cmds:
      - git push origin $(git rev-parse --abbrev-ref HEAD)

