// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.23.3
// source: emis/v1/emis.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Emision struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Codigo    string `protobuf:"bytes,1,opt,name=codigo,proto3" json:"codigo,omitempty"`
	Organismo string `protobuf:"bytes,2,opt,name=organismo,proto3" json:"organismo,omitempty"`
	Total     int32  `protobuf:"varint,3,opt,name=total,proto3" json:"total,omitempty"`
}

func (x *Emision) Reset() {
	*x = Emision{}
	if protoimpl.UnsafeEnabled {
		mi := &file_emis_v1_emis_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Emision) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Emision) ProtoMessage() {}

func (x *Emision) ProtoReflect() protoreflect.Message {
	mi := &file_emis_v1_emis_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Emision.ProtoReflect.Descriptor instead.
func (*Emision) Descriptor() ([]byte, []int) {
	return file_emis_v1_emis_proto_rawDescGZIP(), []int{0}
}

func (x *Emision) GetCodigo() string {
	if x != nil {
		return x.Codigo
	}
	return ""
}

func (x *Emision) GetOrganismo() string {
	if x != nil {
		return x.Organismo
	}
	return ""
}

func (x *Emision) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

// -- Get Emision Tipos de Mensajes --
type GetEmisionRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// tipo nombre posicion
	Codigo string `protobuf:"bytes,1,opt,name=codigo,proto3" json:"codigo,omitempty"`
}

func (x *GetEmisionRequest) Reset() {
	*x = GetEmisionRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_emis_v1_emis_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetEmisionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEmisionRequest) ProtoMessage() {}

func (x *GetEmisionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_emis_v1_emis_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEmisionRequest.ProtoReflect.Descriptor instead.
func (*GetEmisionRequest) Descriptor() ([]byte, []int) {
	return file_emis_v1_emis_proto_rawDescGZIP(), []int{1}
}

func (x *GetEmisionRequest) GetCodigo() string {
	if x != nil {
		return x.Codigo
	}
	return ""
}

type GetEmisionResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// tipo   nombre    posicion
	Emision *Emision `protobuf:"bytes,1,opt,name=emision,proto3" json:"emision,omitempty"`
}

func (x *GetEmisionResponse) Reset() {
	*x = GetEmisionResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_emis_v1_emis_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetEmisionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEmisionResponse) ProtoMessage() {}

func (x *GetEmisionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_emis_v1_emis_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEmisionResponse.ProtoReflect.Descriptor instead.
func (*GetEmisionResponse) Descriptor() ([]byte, []int) {
	return file_emis_v1_emis_proto_rawDescGZIP(), []int{2}
}

func (x *GetEmisionResponse) GetEmision() *Emision {
	if x != nil {
		return x.Emision
	}
	return nil
}

// -- Add Emision Tipos de Mensajes --
type AddEmisionRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// tipo nombre posicion
	Emision *Emision `protobuf:"bytes,1,opt,name=emision,proto3" json:"emision,omitempty"`
}

func (x *AddEmisionRequest) Reset() {
	*x = AddEmisionRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_emis_v1_emis_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddEmisionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddEmisionRequest) ProtoMessage() {}

func (x *AddEmisionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_emis_v1_emis_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddEmisionRequest.ProtoReflect.Descriptor instead.
func (*AddEmisionRequest) Descriptor() ([]byte, []int) {
	return file_emis_v1_emis_proto_rawDescGZIP(), []int{3}
}

func (x *AddEmisionRequest) GetEmision() *Emision {
	if x != nil {
		return x.Emision
	}
	return nil
}

type AddEmisionResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// tipo   nombre    posicion
	Emision *Emision `protobuf:"bytes,1,opt,name=emision,proto3" json:"emision,omitempty"`
}

func (x *AddEmisionResponse) Reset() {
	*x = AddEmisionResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_emis_v1_emis_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddEmisionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddEmisionResponse) ProtoMessage() {}

func (x *AddEmisionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_emis_v1_emis_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddEmisionResponse.ProtoReflect.Descriptor instead.
func (*AddEmisionResponse) Descriptor() ([]byte, []int) {
	return file_emis_v1_emis_proto_rawDescGZIP(), []int{4}
}

func (x *AddEmisionResponse) GetEmision() *Emision {
	if x != nil {
		return x.Emision
	}
	return nil
}

// -- Delete Emision Tipos de Mensajes --
type DeleteEmisionRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// tipo nombre posicion
	Codigo string `protobuf:"bytes,1,opt,name=codigo,proto3" json:"codigo,omitempty"`
}

func (x *DeleteEmisionRequest) Reset() {
	*x = DeleteEmisionRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_emis_v1_emis_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteEmisionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteEmisionRequest) ProtoMessage() {}

func (x *DeleteEmisionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_emis_v1_emis_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteEmisionRequest.ProtoReflect.Descriptor instead.
func (*DeleteEmisionRequest) Descriptor() ([]byte, []int) {
	return file_emis_v1_emis_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteEmisionRequest) GetCodigo() string {
	if x != nil {
		return x.Codigo
	}
	return ""
}

type DeleteEmisionResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// tipo   nombre    posicion
	Status string `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *DeleteEmisionResponse) Reset() {
	*x = DeleteEmisionResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_emis_v1_emis_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteEmisionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteEmisionResponse) ProtoMessage() {}

func (x *DeleteEmisionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_emis_v1_emis_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteEmisionResponse.ProtoReflect.Descriptor instead.
func (*DeleteEmisionResponse) Descriptor() ([]byte, []int) {
	return file_emis_v1_emis_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteEmisionResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_emis_v1_emis_proto protoreflect.FileDescriptor

var file_emis_v1_emis_proto_rawDesc = []byte{
	0x0a, 0x12, 0x65, 0x6d, 0x69, 0x73, 0x2f, 0x76, 0x31, 0x2f, 0x65, 0x6d, 0x69, 0x73, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x65, 0x6d, 0x69, 0x73, 0x22, 0x55, 0x0a, 0x07, 0x45, 0x6d,
	0x69, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x63, 0x6f, 0x64, 0x69, 0x67, 0x6f, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x63, 0x6f, 0x64, 0x69, 0x67, 0x6f, 0x12, 0x1c, 0x0a,
	0x09, 0x6f, 0x72, 0x67, 0x61, 0x6e, 0x69, 0x73, 0x6d, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x09, 0x6f, 0x72, 0x67, 0x61, 0x6e, 0x69, 0x73, 0x6d, 0x6f, 0x12, 0x14, 0x0a, 0x05, 0x74,
	0x6f, 0x74, 0x61, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x74, 0x6f, 0x74, 0x61,
	0x6c, 0x22, 0x2b, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x45, 0x6d, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x63, 0x6f, 0x64, 0x69, 0x67, 0x6f,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x63, 0x6f, 0x64, 0x69, 0x67, 0x6f, 0x22, 0x3d,
	0x0a, 0x12, 0x47, 0x65, 0x74, 0x45, 0x6d, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x27, 0x0a, 0x07, 0x65, 0x6d, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x65, 0x6d, 0x69, 0x73, 0x2e, 0x45, 0x6d, 0x69,
	0x73, 0x69, 0x6f, 0x6e, 0x52, 0x07, 0x65, 0x6d, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x22, 0x3c, 0x0a,
	0x11, 0x41, 0x64, 0x64, 0x45, 0x6d, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x27, 0x0a, 0x07, 0x65, 0x6d, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x65, 0x6d, 0x69, 0x73, 0x2e, 0x45, 0x6d, 0x69, 0x73, 0x69,
	0x6f, 0x6e, 0x52, 0x07, 0x65, 0x6d, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x22, 0x3d, 0x0a, 0x12, 0x41,
	0x64, 0x64, 0x45, 0x6d, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x27, 0x0a, 0x07, 0x65, 0x6d, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x65, 0x6d, 0x69, 0x73, 0x2e, 0x45, 0x6d, 0x69, 0x73, 0x69, 0x6f,
	0x6e, 0x52, 0x07, 0x65, 0x6d, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x22, 0x2e, 0x0a, 0x14, 0x44, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x45, 0x6d, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x63, 0x6f, 0x64, 0x69, 0x67, 0x6f, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x63, 0x6f, 0x64, 0x69, 0x67, 0x6f, 0x22, 0x2f, 0x0a, 0x15, 0x44, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x45, 0x6d, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x32, 0xd9, 0x01, 0x0a, 0x0b,
	0x45, 0x6d, 0x69, 0x73, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x3f, 0x0a, 0x0a, 0x47,
	0x65, 0x74, 0x45, 0x6d, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x17, 0x2e, 0x65, 0x6d, 0x69, 0x73,
	0x2e, 0x47, 0x65, 0x74, 0x45, 0x6d, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x18, 0x2e, 0x65, 0x6d, 0x69, 0x73, 0x2e, 0x47, 0x65, 0x74, 0x45, 0x6d, 0x69,
	0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3f, 0x0a, 0x0a,
	0x41, 0x64, 0x64, 0x45, 0x6d, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x17, 0x2e, 0x65, 0x6d, 0x69,
	0x73, 0x2e, 0x41, 0x64, 0x64, 0x45, 0x6d, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x65, 0x6d, 0x69, 0x73, 0x2e, 0x41, 0x64, 0x64, 0x45, 0x6d,
	0x69, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x48, 0x0a,
	0x0d, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x45, 0x6d, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x1a,
	0x2e, 0x65, 0x6d, 0x69, 0x73, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x45, 0x6d, 0x69, 0x73,
	0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x65, 0x6d, 0x69,
	0x73, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x45, 0x6d, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x1a, 0x5a, 0x18, 0x64, 0x65, 0x6d, 0x6f, 0x2e,
	0x6d, 0x69, 0x63, 0x72, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x65, 0x6d, 0x69, 0x73,
	0x2f, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_emis_v1_emis_proto_rawDescOnce sync.Once
	file_emis_v1_emis_proto_rawDescData = file_emis_v1_emis_proto_rawDesc
)

func file_emis_v1_emis_proto_rawDescGZIP() []byte {
	file_emis_v1_emis_proto_rawDescOnce.Do(func() {
		file_emis_v1_emis_proto_rawDescData = protoimpl.X.CompressGZIP(file_emis_v1_emis_proto_rawDescData)
	})
	return file_emis_v1_emis_proto_rawDescData
}

var file_emis_v1_emis_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_emis_v1_emis_proto_goTypes = []interface{}{
	(*Emision)(nil),               // 0: emis.Emision
	(*GetEmisionRequest)(nil),     // 1: emis.GetEmisionRequest
	(*GetEmisionResponse)(nil),    // 2: emis.GetEmisionResponse
	(*AddEmisionRequest)(nil),     // 3: emis.AddEmisionRequest
	(*AddEmisionResponse)(nil),    // 4: emis.AddEmisionResponse
	(*DeleteEmisionRequest)(nil),  // 5: emis.DeleteEmisionRequest
	(*DeleteEmisionResponse)(nil), // 6: emis.DeleteEmisionResponse
}
var file_emis_v1_emis_proto_depIdxs = []int32{
	0, // 0: emis.GetEmisionResponse.emision:type_name -> emis.Emision
	0, // 1: emis.AddEmisionRequest.emision:type_name -> emis.Emision
	0, // 2: emis.AddEmisionResponse.emision:type_name -> emis.Emision
	1, // 3: emis.EmisService.GetEmision:input_type -> emis.GetEmisionRequest
	3, // 4: emis.EmisService.AddEmision:input_type -> emis.AddEmisionRequest
	5, // 5: emis.EmisService.DeleteEmision:input_type -> emis.DeleteEmisionRequest
	2, // 6: emis.EmisService.GetEmision:output_type -> emis.GetEmisionResponse
	4, // 7: emis.EmisService.AddEmision:output_type -> emis.AddEmisionResponse
	6, // 8: emis.EmisService.DeleteEmision:output_type -> emis.DeleteEmisionResponse
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_emis_v1_emis_proto_init() }
func file_emis_v1_emis_proto_init() {
	if File_emis_v1_emis_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_emis_v1_emis_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Emision); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_emis_v1_emis_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetEmisionRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_emis_v1_emis_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetEmisionResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_emis_v1_emis_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddEmisionRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_emis_v1_emis_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddEmisionResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_emis_v1_emis_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteEmisionRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_emis_v1_emis_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteEmisionResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_emis_v1_emis_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_emis_v1_emis_proto_goTypes,
		DependencyIndexes: file_emis_v1_emis_proto_depIdxs,
		MessageInfos:      file_emis_v1_emis_proto_msgTypes,
	}.Build()
	File_emis_v1_emis_proto = out.File
	file_emis_v1_emis_proto_rawDesc = nil
	file_emis_v1_emis_proto_goTypes = nil
	file_emis_v1_emis_proto_depIdxs = nil
}
