// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v4.23.3
// source: emis/v1/emis.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// EmisServiceClient is the client API for EmisService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type EmisServiceClient interface {
	// Definimos endpoints
	GetEmision(ctx context.Context, in *GetEmisionRequest, opts ...grpc.CallOption) (*GetEmisionResponse, error)
	AddEmision(ctx context.Context, in *AddEmisionRequest, opts ...grpc.CallOption) (*AddEmisionResponse, error)
	DeleteEmision(ctx context.Context, in *DeleteEmisionRequest, opts ...grpc.CallOption) (*DeleteEmisionResponse, error)
}

type emisServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewEmisServiceClient(cc grpc.ClientConnInterface) EmisServiceClient {
	return &emisServiceClient{cc}
}

func (c *emisServiceClient) GetEmision(ctx context.Context, in *GetEmisionRequest, opts ...grpc.CallOption) (*GetEmisionResponse, error) {
	out := new(GetEmisionResponse)
	err := c.cc.Invoke(ctx, "/emis.EmisService/GetEmision", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *emisServiceClient) AddEmision(ctx context.Context, in *AddEmisionRequest, opts ...grpc.CallOption) (*AddEmisionResponse, error) {
	out := new(AddEmisionResponse)
	err := c.cc.Invoke(ctx, "/emis.EmisService/AddEmision", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *emisServiceClient) DeleteEmision(ctx context.Context, in *DeleteEmisionRequest, opts ...grpc.CallOption) (*DeleteEmisionResponse, error) {
	out := new(DeleteEmisionResponse)
	err := c.cc.Invoke(ctx, "/emis.EmisService/DeleteEmision", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EmisServiceServer is the server API for EmisService service.
// All implementations must embed UnimplementedEmisServiceServer
// for forward compatibility
type EmisServiceServer interface {
	// Definimos endpoints
	GetEmision(context.Context, *GetEmisionRequest) (*GetEmisionResponse, error)
	AddEmision(context.Context, *AddEmisionRequest) (*AddEmisionResponse, error)
	DeleteEmision(context.Context, *DeleteEmisionRequest) (*DeleteEmisionResponse, error)
	mustEmbedUnimplementedEmisServiceServer()
}

// UnimplementedEmisServiceServer must be embedded to have forward compatible implementations.
type UnimplementedEmisServiceServer struct {
}

func (UnimplementedEmisServiceServer) GetEmision(context.Context, *GetEmisionRequest) (*GetEmisionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetEmision not implemented")
}
func (UnimplementedEmisServiceServer) AddEmision(context.Context, *AddEmisionRequest) (*AddEmisionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddEmision not implemented")
}
func (UnimplementedEmisServiceServer) DeleteEmision(context.Context, *DeleteEmisionRequest) (*DeleteEmisionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteEmision not implemented")
}
func (UnimplementedEmisServiceServer) mustEmbedUnimplementedEmisServiceServer() {}

// UnsafeEmisServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EmisServiceServer will
// result in compilation errors.
type UnsafeEmisServiceServer interface {
	mustEmbedUnimplementedEmisServiceServer()
}

func RegisterEmisServiceServer(s grpc.ServiceRegistrar, srv EmisServiceServer) {
	s.RegisterService(&EmisService_ServiceDesc, srv)
}

func _EmisService_GetEmision_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetEmisionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmisServiceServer).GetEmision(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/emis.EmisService/GetEmision",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmisServiceServer).GetEmision(ctx, req.(*GetEmisionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EmisService_AddEmision_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddEmisionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmisServiceServer).AddEmision(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/emis.EmisService/AddEmision",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmisServiceServer).AddEmision(ctx, req.(*AddEmisionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EmisService_DeleteEmision_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteEmisionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmisServiceServer).DeleteEmision(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/emis.EmisService/DeleteEmision",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmisServiceServer).DeleteEmision(ctx, req.(*DeleteEmisionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// EmisService_ServiceDesc is the grpc.ServiceDesc for EmisService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EmisService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "emis.EmisService",
	HandlerType: (*EmisServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetEmision",
			Handler:    _EmisService_GetEmision_Handler,
		},
		{
			MethodName: "AddEmision",
			Handler:    _EmisService_AddEmision_Handler,
		},
		{
			MethodName: "DeleteEmision",
			Handler:    _EmisService_DeleteEmision_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "emis/v1/emis.proto",
}
