// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.6.1
// source: protos/emis/emis.proto

package emis

import (
	context "context"
	empty "github.com/golang/protobuf/ptypes/empty"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// EmisServiceClient is the client API for EmisService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type EmisServiceClient interface {
	// Definimos endpoints
	Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error)
	Reset(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*empty.Empty, error)
	GetEmision(ctx context.Context, in *GetEmisionRequest, opts ...grpc.CallOption) (*GetEmisionResponse, error)
	GetEmisiones(ctx context.Context, in *GetEmisionesRequest, opts ...grpc.CallOption) (*GetEmisionesResponse, error)
	AddEmision(ctx context.Context, in *AddEmisionRequest, opts ...grpc.CallOption) (*AddEmisionResponse, error)
	DeleteEmision(ctx context.Context, in *DeleteEmisionRequest, opts ...grpc.CallOption) (*DeleteEmisionResponse, error)
	FakeEmision(ctx context.Context, in *FakeEmisionRequest, opts ...grpc.CallOption) (*FakeEmisionResponse, error)
	InitEmision(ctx context.Context, in *InitEmisionRequest, opts ...grpc.CallOption) (*InitEmisionResponse, error)
	// Recibos
	GetRecibo(ctx context.Context, in *GetReciboRequest, opts ...grpc.CallOption) (*GetReciboResponse, error)
	GetRecibos(ctx context.Context, in *GetRecibosRequest, opts ...grpc.CallOption) (*GetRecibosResponse, error)
	AddRecibo(ctx context.Context, in *AddReciboRequest, opts ...grpc.CallOption) (*AddReciboResponse, error)
	DeleteRecibo(ctx context.Context, in *DeleteReciboRequest, opts ...grpc.CallOption) (*DeleteReciboResponse, error)
	UpdatePdfRecibo(ctx context.Context, in *UpdatePdfReciboRequest, opts ...grpc.CallOption) (*UpdatePdfReciboResponse, error)
}

type emisServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewEmisServiceClient(cc grpc.ClientConnInterface) EmisServiceClient {
	return &emisServiceClient{cc}
}

func (c *emisServiceClient) Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error) {
	out := new(PingResponse)
	err := c.cc.Invoke(ctx, "/EmisService/Ping", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *emisServiceClient) Reset(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/EmisService/Reset", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *emisServiceClient) GetEmision(ctx context.Context, in *GetEmisionRequest, opts ...grpc.CallOption) (*GetEmisionResponse, error) {
	out := new(GetEmisionResponse)
	err := c.cc.Invoke(ctx, "/EmisService/GetEmision", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *emisServiceClient) GetEmisiones(ctx context.Context, in *GetEmisionesRequest, opts ...grpc.CallOption) (*GetEmisionesResponse, error) {
	out := new(GetEmisionesResponse)
	err := c.cc.Invoke(ctx, "/EmisService/GetEmisiones", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *emisServiceClient) AddEmision(ctx context.Context, in *AddEmisionRequest, opts ...grpc.CallOption) (*AddEmisionResponse, error) {
	out := new(AddEmisionResponse)
	err := c.cc.Invoke(ctx, "/EmisService/AddEmision", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *emisServiceClient) DeleteEmision(ctx context.Context, in *DeleteEmisionRequest, opts ...grpc.CallOption) (*DeleteEmisionResponse, error) {
	out := new(DeleteEmisionResponse)
	err := c.cc.Invoke(ctx, "/EmisService/DeleteEmision", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *emisServiceClient) FakeEmision(ctx context.Context, in *FakeEmisionRequest, opts ...grpc.CallOption) (*FakeEmisionResponse, error) {
	out := new(FakeEmisionResponse)
	err := c.cc.Invoke(ctx, "/EmisService/FakeEmision", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *emisServiceClient) InitEmision(ctx context.Context, in *InitEmisionRequest, opts ...grpc.CallOption) (*InitEmisionResponse, error) {
	out := new(InitEmisionResponse)
	err := c.cc.Invoke(ctx, "/EmisService/InitEmision", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *emisServiceClient) GetRecibo(ctx context.Context, in *GetReciboRequest, opts ...grpc.CallOption) (*GetReciboResponse, error) {
	out := new(GetReciboResponse)
	err := c.cc.Invoke(ctx, "/EmisService/GetRecibo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *emisServiceClient) GetRecibos(ctx context.Context, in *GetRecibosRequest, opts ...grpc.CallOption) (*GetRecibosResponse, error) {
	out := new(GetRecibosResponse)
	err := c.cc.Invoke(ctx, "/EmisService/GetRecibos", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *emisServiceClient) AddRecibo(ctx context.Context, in *AddReciboRequest, opts ...grpc.CallOption) (*AddReciboResponse, error) {
	out := new(AddReciboResponse)
	err := c.cc.Invoke(ctx, "/EmisService/AddRecibo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *emisServiceClient) DeleteRecibo(ctx context.Context, in *DeleteReciboRequest, opts ...grpc.CallOption) (*DeleteReciboResponse, error) {
	out := new(DeleteReciboResponse)
	err := c.cc.Invoke(ctx, "/EmisService/DeleteRecibo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *emisServiceClient) UpdatePdfRecibo(ctx context.Context, in *UpdatePdfReciboRequest, opts ...grpc.CallOption) (*UpdatePdfReciboResponse, error) {
	out := new(UpdatePdfReciboResponse)
	err := c.cc.Invoke(ctx, "/EmisService/UpdatePdfRecibo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EmisServiceServer is the server API for EmisService service.
// All implementations must embed UnimplementedEmisServiceServer
// for forward compatibility
type EmisServiceServer interface {
	// Definimos endpoints
	Ping(context.Context, *PingRequest) (*PingResponse, error)
	Reset(context.Context, *empty.Empty) (*empty.Empty, error)
	GetEmision(context.Context, *GetEmisionRequest) (*GetEmisionResponse, error)
	GetEmisiones(context.Context, *GetEmisionesRequest) (*GetEmisionesResponse, error)
	AddEmision(context.Context, *AddEmisionRequest) (*AddEmisionResponse, error)
	DeleteEmision(context.Context, *DeleteEmisionRequest) (*DeleteEmisionResponse, error)
	FakeEmision(context.Context, *FakeEmisionRequest) (*FakeEmisionResponse, error)
	InitEmision(context.Context, *InitEmisionRequest) (*InitEmisionResponse, error)
	// Recibos
	GetRecibo(context.Context, *GetReciboRequest) (*GetReciboResponse, error)
	GetRecibos(context.Context, *GetRecibosRequest) (*GetRecibosResponse, error)
	AddRecibo(context.Context, *AddReciboRequest) (*AddReciboResponse, error)
	DeleteRecibo(context.Context, *DeleteReciboRequest) (*DeleteReciboResponse, error)
	UpdatePdfRecibo(context.Context, *UpdatePdfReciboRequest) (*UpdatePdfReciboResponse, error)
	mustEmbedUnimplementedEmisServiceServer()
}

// UnimplementedEmisServiceServer must be embedded to have forward compatible implementations.
type UnimplementedEmisServiceServer struct {
}

func (UnimplementedEmisServiceServer) Ping(context.Context, *PingRequest) (*PingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedEmisServiceServer) Reset(context.Context, *empty.Empty) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Reset not implemented")
}
func (UnimplementedEmisServiceServer) GetEmision(context.Context, *GetEmisionRequest) (*GetEmisionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetEmision not implemented")
}
func (UnimplementedEmisServiceServer) GetEmisiones(context.Context, *GetEmisionesRequest) (*GetEmisionesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetEmisiones not implemented")
}
func (UnimplementedEmisServiceServer) AddEmision(context.Context, *AddEmisionRequest) (*AddEmisionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddEmision not implemented")
}
func (UnimplementedEmisServiceServer) DeleteEmision(context.Context, *DeleteEmisionRequest) (*DeleteEmisionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteEmision not implemented")
}
func (UnimplementedEmisServiceServer) FakeEmision(context.Context, *FakeEmisionRequest) (*FakeEmisionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FakeEmision not implemented")
}
func (UnimplementedEmisServiceServer) InitEmision(context.Context, *InitEmisionRequest) (*InitEmisionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InitEmision not implemented")
}
func (UnimplementedEmisServiceServer) GetRecibo(context.Context, *GetReciboRequest) (*GetReciboResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRecibo not implemented")
}
func (UnimplementedEmisServiceServer) GetRecibos(context.Context, *GetRecibosRequest) (*GetRecibosResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRecibos not implemented")
}
func (UnimplementedEmisServiceServer) AddRecibo(context.Context, *AddReciboRequest) (*AddReciboResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddRecibo not implemented")
}
func (UnimplementedEmisServiceServer) DeleteRecibo(context.Context, *DeleteReciboRequest) (*DeleteReciboResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteRecibo not implemented")
}
func (UnimplementedEmisServiceServer) UpdatePdfRecibo(context.Context, *UpdatePdfReciboRequest) (*UpdatePdfReciboResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdatePdfRecibo not implemented")
}
func (UnimplementedEmisServiceServer) mustEmbedUnimplementedEmisServiceServer() {}

// UnsafeEmisServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EmisServiceServer will
// result in compilation errors.
type UnsafeEmisServiceServer interface {
	mustEmbedUnimplementedEmisServiceServer()
}

func RegisterEmisServiceServer(s grpc.ServiceRegistrar, srv EmisServiceServer) {
	s.RegisterService(&EmisService_ServiceDesc, srv)
}

func _EmisService_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmisServiceServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/EmisService/Ping",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmisServiceServer).Ping(ctx, req.(*PingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EmisService_Reset_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmisServiceServer).Reset(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/EmisService/Reset",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmisServiceServer).Reset(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _EmisService_GetEmision_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetEmisionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmisServiceServer).GetEmision(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/EmisService/GetEmision",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmisServiceServer).GetEmision(ctx, req.(*GetEmisionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EmisService_GetEmisiones_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetEmisionesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmisServiceServer).GetEmisiones(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/EmisService/GetEmisiones",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmisServiceServer).GetEmisiones(ctx, req.(*GetEmisionesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EmisService_AddEmision_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddEmisionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmisServiceServer).AddEmision(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/EmisService/AddEmision",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmisServiceServer).AddEmision(ctx, req.(*AddEmisionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EmisService_DeleteEmision_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteEmisionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmisServiceServer).DeleteEmision(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/EmisService/DeleteEmision",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmisServiceServer).DeleteEmision(ctx, req.(*DeleteEmisionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EmisService_FakeEmision_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FakeEmisionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmisServiceServer).FakeEmision(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/EmisService/FakeEmision",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmisServiceServer).FakeEmision(ctx, req.(*FakeEmisionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EmisService_InitEmision_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InitEmisionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmisServiceServer).InitEmision(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/EmisService/InitEmision",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmisServiceServer).InitEmision(ctx, req.(*InitEmisionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EmisService_GetRecibo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetReciboRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmisServiceServer).GetRecibo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/EmisService/GetRecibo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmisServiceServer).GetRecibo(ctx, req.(*GetReciboRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EmisService_GetRecibos_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRecibosRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmisServiceServer).GetRecibos(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/EmisService/GetRecibos",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmisServiceServer).GetRecibos(ctx, req.(*GetRecibosRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EmisService_AddRecibo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddReciboRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmisServiceServer).AddRecibo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/EmisService/AddRecibo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmisServiceServer).AddRecibo(ctx, req.(*AddReciboRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EmisService_DeleteRecibo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteReciboRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmisServiceServer).DeleteRecibo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/EmisService/DeleteRecibo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmisServiceServer).DeleteRecibo(ctx, req.(*DeleteReciboRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EmisService_UpdatePdfRecibo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdatePdfReciboRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmisServiceServer).UpdatePdfRecibo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/EmisService/UpdatePdfRecibo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmisServiceServer).UpdatePdfRecibo(ctx, req.(*UpdatePdfReciboRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// EmisService_ServiceDesc is the grpc.ServiceDesc for EmisService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EmisService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "EmisService",
	HandlerType: (*EmisServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _EmisService_Ping_Handler,
		},
		{
			MethodName: "Reset",
			Handler:    _EmisService_Reset_Handler,
		},
		{
			MethodName: "GetEmision",
			Handler:    _EmisService_GetEmision_Handler,
		},
		{
			MethodName: "GetEmisiones",
			Handler:    _EmisService_GetEmisiones_Handler,
		},
		{
			MethodName: "AddEmision",
			Handler:    _EmisService_AddEmision_Handler,
		},
		{
			MethodName: "DeleteEmision",
			Handler:    _EmisService_DeleteEmision_Handler,
		},
		{
			MethodName: "FakeEmision",
			Handler:    _EmisService_FakeEmision_Handler,
		},
		{
			MethodName: "InitEmision",
			Handler:    _EmisService_InitEmision_Handler,
		},
		{
			MethodName: "GetRecibo",
			Handler:    _EmisService_GetRecibo_Handler,
		},
		{
			MethodName: "GetRecibos",
			Handler:    _EmisService_GetRecibos_Handler,
		},
		{
			MethodName: "AddRecibo",
			Handler:    _EmisService_AddRecibo_Handler,
		},
		{
			MethodName: "DeleteRecibo",
			Handler:    _EmisService_DeleteRecibo_Handler,
		},
		{
			MethodName: "UpdatePdfRecibo",
			Handler:    _EmisService_UpdatePdfRecibo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protos/emis/emis.proto",
}
