// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.6.1
// source: protos/emis/emis.proto

package emis

import (
	empty "github.com/golang/protobuf/ptypes/empty"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Emision struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Codigo          string `protobuf:"bytes,1,opt,name=codigo,proto3" json:"codigo,omitempty"`
	Organismo       string `protobuf:"bytes,2,opt,name=organismo,proto3" json:"organismo,omitempty"`
	TotalDocumentos int32  `protobuf:"varint,3,opt,name=total_documentos,json=totalDocumentos,proto3" json:"total_documentos,omitempty"`
	Descripcion     string `protobuf:"bytes,4,opt,name=descripcion,proto3" json:"descripcion,omitempty"`
	Firmar          bool   `protobuf:"varint,5,opt,name=firmar,proto3" json:"firmar,omitempty"`
	SelloTiempo     bool   `protobuf:"varint,6,opt,name=sello_tiempo,json=selloTiempo,proto3" json:"sello_tiempo,omitempty"`
	Notificar       bool   `protobuf:"varint,7,opt,name=notificar,proto3" json:"notificar,omitempty"`
	Status          string `protobuf:"bytes,8,opt,name=status,proto3" json:"status,omitempty"`
	TamanioBloque   int32  `protobuf:"varint,9,opt,name=tamanio_bloque,json=tamanioBloque,proto3" json:"tamanio_bloque,omitempty"`
}

func (x *Emision) Reset() {
	*x = Emision{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_emis_emis_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Emision) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Emision) ProtoMessage() {}

func (x *Emision) ProtoReflect() protoreflect.Message {
	mi := &file_protos_emis_emis_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Emision.ProtoReflect.Descriptor instead.
func (*Emision) Descriptor() ([]byte, []int) {
	return file_protos_emis_emis_proto_rawDescGZIP(), []int{0}
}

func (x *Emision) GetCodigo() string {
	if x != nil {
		return x.Codigo
	}
	return ""
}

func (x *Emision) GetOrganismo() string {
	if x != nil {
		return x.Organismo
	}
	return ""
}

func (x *Emision) GetTotalDocumentos() int32 {
	if x != nil {
		return x.TotalDocumentos
	}
	return 0
}

func (x *Emision) GetDescripcion() string {
	if x != nil {
		return x.Descripcion
	}
	return ""
}

func (x *Emision) GetFirmar() bool {
	if x != nil {
		return x.Firmar
	}
	return false
}

func (x *Emision) GetSelloTiempo() bool {
	if x != nil {
		return x.SelloTiempo
	}
	return false
}

func (x *Emision) GetNotificar() bool {
	if x != nil {
		return x.Notificar
	}
	return false
}

func (x *Emision) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Emision) GetTamanioBloque() int32 {
	if x != nil {
		return x.TamanioBloque
	}
	return 0
}

type Recibo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CodEmision    string `protobuf:"bytes,1,opt,name=cod_emision,json=codEmision,proto3" json:"cod_emision,omitempty"`
	NumOrden      int32  `protobuf:"varint,2,opt,name=num_orden,json=numOrden,proto3" json:"num_orden,omitempty"`
	Nombre        string `protobuf:"bytes,3,opt,name=nombre,proto3" json:"nombre,omitempty"`
	Apellidos     string `protobuf:"bytes,4,opt,name=apellidos,proto3" json:"apellidos,omitempty"`
	Concepto      string `protobuf:"bytes,5,opt,name=concepto,proto3" json:"concepto,omitempty"`
	Importe       int32  `protobuf:"varint,6,opt,name=importe,proto3" json:"importe,omitempty"`
	Email         string `protobuf:"bytes,7,opt,name=email,proto3" json:"email,omitempty"`
	Telefono      string `protobuf:"bytes,8,opt,name=telefono,proto3" json:"telefono,omitempty"`
	Observaciones string `protobuf:"bytes,9,opt,name=observaciones,proto3" json:"observaciones,omitempty"`
	Pdf           string `protobuf:"bytes,10,opt,name=pdf,proto3" json:"pdf,omitempty"`
	Tamanio       int32  `protobuf:"varint,11,opt,name=tamanio,proto3" json:"tamanio,omitempty"`
}

func (x *Recibo) Reset() {
	*x = Recibo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_emis_emis_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Recibo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Recibo) ProtoMessage() {}

func (x *Recibo) ProtoReflect() protoreflect.Message {
	mi := &file_protos_emis_emis_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Recibo.ProtoReflect.Descriptor instead.
func (*Recibo) Descriptor() ([]byte, []int) {
	return file_protos_emis_emis_proto_rawDescGZIP(), []int{1}
}

func (x *Recibo) GetCodEmision() string {
	if x != nil {
		return x.CodEmision
	}
	return ""
}

func (x *Recibo) GetNumOrden() int32 {
	if x != nil {
		return x.NumOrden
	}
	return 0
}

func (x *Recibo) GetNombre() string {
	if x != nil {
		return x.Nombre
	}
	return ""
}

func (x *Recibo) GetApellidos() string {
	if x != nil {
		return x.Apellidos
	}
	return ""
}

func (x *Recibo) GetConcepto() string {
	if x != nil {
		return x.Concepto
	}
	return ""
}

func (x *Recibo) GetImporte() int32 {
	if x != nil {
		return x.Importe
	}
	return 0
}

func (x *Recibo) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *Recibo) GetTelefono() string {
	if x != nil {
		return x.Telefono
	}
	return ""
}

func (x *Recibo) GetObservaciones() string {
	if x != nil {
		return x.Observaciones
	}
	return ""
}

func (x *Recibo) GetPdf() string {
	if x != nil {
		return x.Pdf
	}
	return ""
}

func (x *Recibo) GetTamanio() int32 {
	if x != nil {
		return x.Tamanio
	}
	return 0
}

// -- Ping  Tipos de Mensajes --
type PingRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Msg string `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_emis_emis_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_emis_emis_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_protos_emis_emis_proto_rawDescGZIP(), []int{2}
}

func (x *PingRequest) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type PingResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// tipo   nombre    posicion
	Reply string `protobuf:"bytes,1,opt,name=reply,proto3" json:"reply,omitempty"`
}

func (x *PingResponse) Reset() {
	*x = PingResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_emis_emis_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResponse) ProtoMessage() {}

func (x *PingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_emis_emis_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResponse.ProtoReflect.Descriptor instead.
func (*PingResponse) Descriptor() ([]byte, []int) {
	return file_protos_emis_emis_proto_rawDescGZIP(), []int{3}
}

func (x *PingResponse) GetReply() string {
	if x != nil {
		return x.Reply
	}
	return ""
}

// -- Get Emision Tipos de Mensajes --
type GetEmisionRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// tipo nombre posicion
	Codigo string `protobuf:"bytes,1,opt,name=codigo,proto3" json:"codigo,omitempty"`
}

func (x *GetEmisionRequest) Reset() {
	*x = GetEmisionRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_emis_emis_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetEmisionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEmisionRequest) ProtoMessage() {}

func (x *GetEmisionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_emis_emis_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEmisionRequest.ProtoReflect.Descriptor instead.
func (*GetEmisionRequest) Descriptor() ([]byte, []int) {
	return file_protos_emis_emis_proto_rawDescGZIP(), []int{4}
}

func (x *GetEmisionRequest) GetCodigo() string {
	if x != nil {
		return x.Codigo
	}
	return ""
}

type GetEmisionResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// tipo   nombre    posicion
	Emision *Emision `protobuf:"bytes,1,opt,name=emision,proto3" json:"emision,omitempty"`
}

func (x *GetEmisionResponse) Reset() {
	*x = GetEmisionResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_emis_emis_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetEmisionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEmisionResponse) ProtoMessage() {}

func (x *GetEmisionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_emis_emis_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEmisionResponse.ProtoReflect.Descriptor instead.
func (*GetEmisionResponse) Descriptor() ([]byte, []int) {
	return file_protos_emis_emis_proto_rawDescGZIP(), []int{5}
}

func (x *GetEmisionResponse) GetEmision() *Emision {
	if x != nil {
		return x.Emision
	}
	return nil
}

// -- Get Emisiones Tipos de Mensajes --
type GetEmisionesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetEmisionesRequest) Reset() {
	*x = GetEmisionesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_emis_emis_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetEmisionesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEmisionesRequest) ProtoMessage() {}

func (x *GetEmisionesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_emis_emis_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEmisionesRequest.ProtoReflect.Descriptor instead.
func (*GetEmisionesRequest) Descriptor() ([]byte, []int) {
	return file_protos_emis_emis_proto_rawDescGZIP(), []int{6}
}

type GetEmisionesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// tipo   nombre    posicion
	Emisiones []*Emision `protobuf:"bytes,1,rep,name=emisiones,proto3" json:"emisiones,omitempty"`
}

func (x *GetEmisionesResponse) Reset() {
	*x = GetEmisionesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_emis_emis_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetEmisionesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEmisionesResponse) ProtoMessage() {}

func (x *GetEmisionesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_emis_emis_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEmisionesResponse.ProtoReflect.Descriptor instead.
func (*GetEmisionesResponse) Descriptor() ([]byte, []int) {
	return file_protos_emis_emis_proto_rawDescGZIP(), []int{7}
}

func (x *GetEmisionesResponse) GetEmisiones() []*Emision {
	if x != nil {
		return x.Emisiones
	}
	return nil
}

// -- Add Emision Tipos de Mensajes --
type AddEmisionRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// tipo nombre posicion
	Emision *Emision `protobuf:"bytes,1,opt,name=emision,proto3" json:"emision,omitempty"`
}

func (x *AddEmisionRequest) Reset() {
	*x = AddEmisionRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_emis_emis_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddEmisionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddEmisionRequest) ProtoMessage() {}

func (x *AddEmisionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_emis_emis_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddEmisionRequest.ProtoReflect.Descriptor instead.
func (*AddEmisionRequest) Descriptor() ([]byte, []int) {
	return file_protos_emis_emis_proto_rawDescGZIP(), []int{8}
}

func (x *AddEmisionRequest) GetEmision() *Emision {
	if x != nil {
		return x.Emision
	}
	return nil
}

type AddEmisionResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// tipo   nombre    posicion
	Emision *Emision `protobuf:"bytes,1,opt,name=emision,proto3" json:"emision,omitempty"`
}

func (x *AddEmisionResponse) Reset() {
	*x = AddEmisionResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_emis_emis_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddEmisionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddEmisionResponse) ProtoMessage() {}

func (x *AddEmisionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_emis_emis_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddEmisionResponse.ProtoReflect.Descriptor instead.
func (*AddEmisionResponse) Descriptor() ([]byte, []int) {
	return file_protos_emis_emis_proto_rawDescGZIP(), []int{9}
}

func (x *AddEmisionResponse) GetEmision() *Emision {
	if x != nil {
		return x.Emision
	}
	return nil
}

// -- Delete Emision Tipos de Mensajes --
type DeleteEmisionRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// tipo nombre posicion
	Codigo string `protobuf:"bytes,1,opt,name=codigo,proto3" json:"codigo,omitempty"`
}

func (x *DeleteEmisionRequest) Reset() {
	*x = DeleteEmisionRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_emis_emis_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteEmisionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteEmisionRequest) ProtoMessage() {}

func (x *DeleteEmisionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_emis_emis_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteEmisionRequest.ProtoReflect.Descriptor instead.
func (*DeleteEmisionRequest) Descriptor() ([]byte, []int) {
	return file_protos_emis_emis_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteEmisionRequest) GetCodigo() string {
	if x != nil {
		return x.Codigo
	}
	return ""
}

type DeleteEmisionResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// tipo   nombre    posicion
	Status string `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Total  int32  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
}

func (x *DeleteEmisionResponse) Reset() {
	*x = DeleteEmisionResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_emis_emis_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteEmisionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteEmisionResponse) ProtoMessage() {}

func (x *DeleteEmisionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_emis_emis_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteEmisionResponse.ProtoReflect.Descriptor instead.
func (*DeleteEmisionResponse) Descriptor() ([]byte, []int) {
	return file_protos_emis_emis_proto_rawDescGZIP(), []int{11}
}

func (x *DeleteEmisionResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *DeleteEmisionResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

// -- Fake Emision Tipos de Mensajes --
type FakeEmisionRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// tipo nombre posicion
	Codigo string `protobuf:"bytes,1,opt,name=codigo,proto3" json:"codigo,omitempty"`
}

func (x *FakeEmisionRequest) Reset() {
	*x = FakeEmisionRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_emis_emis_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FakeEmisionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FakeEmisionRequest) ProtoMessage() {}

func (x *FakeEmisionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_emis_emis_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FakeEmisionRequest.ProtoReflect.Descriptor instead.
func (*FakeEmisionRequest) Descriptor() ([]byte, []int) {
	return file_protos_emis_emis_proto_rawDescGZIP(), []int{12}
}

func (x *FakeEmisionRequest) GetCodigo() string {
	if x != nil {
		return x.Codigo
	}
	return ""
}

type FakeEmisionResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Total de documentos procesados.
	Total int32 `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
}

func (x *FakeEmisionResponse) Reset() {
	*x = FakeEmisionResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_emis_emis_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FakeEmisionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FakeEmisionResponse) ProtoMessage() {}

func (x *FakeEmisionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_emis_emis_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FakeEmisionResponse.ProtoReflect.Descriptor instead.
func (*FakeEmisionResponse) Descriptor() ([]byte, []int) {
	return file_protos_emis_emis_proto_rawDescGZIP(), []int{13}
}

func (x *FakeEmisionResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

// -- Init Emision Tipos de Mensajes --
type InitEmisionRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// tipo nombre posicion
	Codigo string `protobuf:"bytes,1,opt,name=codigo,proto3" json:"codigo,omitempty"`
}

func (x *InitEmisionRequest) Reset() {
	*x = InitEmisionRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_emis_emis_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InitEmisionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitEmisionRequest) ProtoMessage() {}

func (x *InitEmisionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_emis_emis_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitEmisionRequest.ProtoReflect.Descriptor instead.
func (*InitEmisionRequest) Descriptor() ([]byte, []int) {
	return file_protos_emis_emis_proto_rawDescGZIP(), []int{14}
}

func (x *InitEmisionRequest) GetCodigo() string {
	if x != nil {
		return x.Codigo
	}
	return ""
}

type InitEmisionResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *InitEmisionResponse) Reset() {
	*x = InitEmisionResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_emis_emis_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InitEmisionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitEmisionResponse) ProtoMessage() {}

func (x *InitEmisionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_emis_emis_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitEmisionResponse.ProtoReflect.Descriptor instead.
func (*InitEmisionResponse) Descriptor() ([]byte, []int) {
	return file_protos_emis_emis_proto_rawDescGZIP(), []int{15}
}

// ==================
// Recibos
// ==================
// -- Get Recibo Tipos de Mensajes --
type GetReciboRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// tipo nombre posicion
	CodigoEmision string `protobuf:"bytes,1,opt,name=codigo_emision,json=codigoEmision,proto3" json:"codigo_emision,omitempty"`
	NumeroOrden   int32  `protobuf:"varint,2,opt,name=numero_orden,json=numeroOrden,proto3" json:"numero_orden,omitempty"`
	IncluirPdf    bool   `protobuf:"varint,3,opt,name=incluir_pdf,json=incluirPdf,proto3" json:"incluir_pdf,omitempty"`
}

func (x *GetReciboRequest) Reset() {
	*x = GetReciboRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_emis_emis_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetReciboRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReciboRequest) ProtoMessage() {}

func (x *GetReciboRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_emis_emis_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReciboRequest.ProtoReflect.Descriptor instead.
func (*GetReciboRequest) Descriptor() ([]byte, []int) {
	return file_protos_emis_emis_proto_rawDescGZIP(), []int{16}
}

func (x *GetReciboRequest) GetCodigoEmision() string {
	if x != nil {
		return x.CodigoEmision
	}
	return ""
}

func (x *GetReciboRequest) GetNumeroOrden() int32 {
	if x != nil {
		return x.NumeroOrden
	}
	return 0
}

func (x *GetReciboRequest) GetIncluirPdf() bool {
	if x != nil {
		return x.IncluirPdf
	}
	return false
}

type GetReciboResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// tipo   nombre    posicion
	Recibo *Recibo `protobuf:"bytes,1,opt,name=recibo,proto3" json:"recibo,omitempty"`
}

func (x *GetReciboResponse) Reset() {
	*x = GetReciboResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_emis_emis_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetReciboResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReciboResponse) ProtoMessage() {}

func (x *GetReciboResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_emis_emis_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReciboResponse.ProtoReflect.Descriptor instead.
func (*GetReciboResponse) Descriptor() ([]byte, []int) {
	return file_protos_emis_emis_proto_rawDescGZIP(), []int{17}
}

func (x *GetReciboResponse) GetRecibo() *Recibo {
	if x != nil {
		return x.Recibo
	}
	return nil
}

type GetRecibosRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// tipo nombre posicion
	CodigoEmision string `protobuf:"bytes,1,opt,name=codigo_emision,json=codigoEmision,proto3" json:"codigo_emision,omitempty"`
	Bloque        int32  `protobuf:"varint,2,opt,name=bloque,proto3" json:"bloque,omitempty"`
}

func (x *GetRecibosRequest) Reset() {
	*x = GetRecibosRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_emis_emis_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetRecibosRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRecibosRequest) ProtoMessage() {}

func (x *GetRecibosRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_emis_emis_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRecibosRequest.ProtoReflect.Descriptor instead.
func (*GetRecibosRequest) Descriptor() ([]byte, []int) {
	return file_protos_emis_emis_proto_rawDescGZIP(), []int{18}
}

func (x *GetRecibosRequest) GetCodigoEmision() string {
	if x != nil {
		return x.CodigoEmision
	}
	return ""
}

func (x *GetRecibosRequest) GetBloque() int32 {
	if x != nil {
		return x.Bloque
	}
	return 0
}

type GetRecibosResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// tipo   nombre    posicion
	Recibos []*Recibo `protobuf:"bytes,1,rep,name=recibos,proto3" json:"recibos,omitempty"`
}

func (x *GetRecibosResponse) Reset() {
	*x = GetRecibosResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_emis_emis_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetRecibosResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRecibosResponse) ProtoMessage() {}

func (x *GetRecibosResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_emis_emis_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRecibosResponse.ProtoReflect.Descriptor instead.
func (*GetRecibosResponse) Descriptor() ([]byte, []int) {
	return file_protos_emis_emis_proto_rawDescGZIP(), []int{19}
}

func (x *GetRecibosResponse) GetRecibos() []*Recibo {
	if x != nil {
		return x.Recibos
	}
	return nil
}

// -- Add Recibo Tipos de Mensajes --
type AddReciboRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// tipo nombre posicion
	Recibo *Recibo `protobuf:"bytes,1,opt,name=recibo,proto3" json:"recibo,omitempty"`
}

func (x *AddReciboRequest) Reset() {
	*x = AddReciboRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_emis_emis_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddReciboRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddReciboRequest) ProtoMessage() {}

func (x *AddReciboRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_emis_emis_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddReciboRequest.ProtoReflect.Descriptor instead.
func (*AddReciboRequest) Descriptor() ([]byte, []int) {
	return file_protos_emis_emis_proto_rawDescGZIP(), []int{20}
}

func (x *AddReciboRequest) GetRecibo() *Recibo {
	if x != nil {
		return x.Recibo
	}
	return nil
}

type AddReciboResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// tipo   nombre    posicion
	Recibo *Recibo `protobuf:"bytes,1,opt,name=recibo,proto3" json:"recibo,omitempty"`
}

func (x *AddReciboResponse) Reset() {
	*x = AddReciboResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_emis_emis_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddReciboResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddReciboResponse) ProtoMessage() {}

func (x *AddReciboResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_emis_emis_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddReciboResponse.ProtoReflect.Descriptor instead.
func (*AddReciboResponse) Descriptor() ([]byte, []int) {
	return file_protos_emis_emis_proto_rawDescGZIP(), []int{21}
}

func (x *AddReciboResponse) GetRecibo() *Recibo {
	if x != nil {
		return x.Recibo
	}
	return nil
}

// -- Delete Recibo Tipos de Mensajes --
type DeleteReciboRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// tipo nombre posicion
	CodigoEmision string `protobuf:"bytes,1,opt,name=codigo_emision,json=codigoEmision,proto3" json:"codigo_emision,omitempty"`
	NumeroOrden   int32  `protobuf:"varint,2,opt,name=numero_orden,json=numeroOrden,proto3" json:"numero_orden,omitempty"`
}

func (x *DeleteReciboRequest) Reset() {
	*x = DeleteReciboRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_emis_emis_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteReciboRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteReciboRequest) ProtoMessage() {}

func (x *DeleteReciboRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_emis_emis_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteReciboRequest.ProtoReflect.Descriptor instead.
func (*DeleteReciboRequest) Descriptor() ([]byte, []int) {
	return file_protos_emis_emis_proto_rawDescGZIP(), []int{22}
}

func (x *DeleteReciboRequest) GetCodigoEmision() string {
	if x != nil {
		return x.CodigoEmision
	}
	return ""
}

func (x *DeleteReciboRequest) GetNumeroOrden() int32 {
	if x != nil {
		return x.NumeroOrden
	}
	return 0
}

type DeleteReciboResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// tipo   nombre    posicion
	Status string `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Total  int32  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
}

func (x *DeleteReciboResponse) Reset() {
	*x = DeleteReciboResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_emis_emis_proto_msgTypes[23]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteReciboResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteReciboResponse) ProtoMessage() {}

func (x *DeleteReciboResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_emis_emis_proto_msgTypes[23]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteReciboResponse.ProtoReflect.Descriptor instead.
func (*DeleteReciboResponse) Descriptor() ([]byte, []int) {
	return file_protos_emis_emis_proto_rawDescGZIP(), []int{23}
}

func (x *DeleteReciboResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *DeleteReciboResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

// -- UpdatePdf Recibo Tipos de Mensajes --
type UpdatePdfReciboRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// tipo nombre posicion
	CodigoEmision string `protobuf:"bytes,1,opt,name=codigo_emision,json=codigoEmision,proto3" json:"codigo_emision,omitempty"`
	NumeroOrden   int32  `protobuf:"varint,2,opt,name=numero_orden,json=numeroOrden,proto3" json:"numero_orden,omitempty"`
	Pdf           string `protobuf:"bytes,3,opt,name=pdf,proto3" json:"pdf,omitempty"`
}

func (x *UpdatePdfReciboRequest) Reset() {
	*x = UpdatePdfReciboRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_emis_emis_proto_msgTypes[24]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdatePdfReciboRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePdfReciboRequest) ProtoMessage() {}

func (x *UpdatePdfReciboRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_emis_emis_proto_msgTypes[24]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePdfReciboRequest.ProtoReflect.Descriptor instead.
func (*UpdatePdfReciboRequest) Descriptor() ([]byte, []int) {
	return file_protos_emis_emis_proto_rawDescGZIP(), []int{24}
}

func (x *UpdatePdfReciboRequest) GetCodigoEmision() string {
	if x != nil {
		return x.CodigoEmision
	}
	return ""
}

func (x *UpdatePdfReciboRequest) GetNumeroOrden() int32 {
	if x != nil {
		return x.NumeroOrden
	}
	return 0
}

func (x *UpdatePdfReciboRequest) GetPdf() string {
	if x != nil {
		return x.Pdf
	}
	return ""
}

type UpdatePdfReciboResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// tipo   nombre    posicion
	Tamanio int32 `protobuf:"varint,1,opt,name=tamanio,proto3" json:"tamanio,omitempty"`
}

func (x *UpdatePdfReciboResponse) Reset() {
	*x = UpdatePdfReciboResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_emis_emis_proto_msgTypes[25]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdatePdfReciboResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePdfReciboResponse) ProtoMessage() {}

func (x *UpdatePdfReciboResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_emis_emis_proto_msgTypes[25]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePdfReciboResponse.ProtoReflect.Descriptor instead.
func (*UpdatePdfReciboResponse) Descriptor() ([]byte, []int) {
	return file_protos_emis_emis_proto_rawDescGZIP(), []int{25}
}

func (x *UpdatePdfReciboResponse) GetTamanio() int32 {
	if x != nil {
		return x.Tamanio
	}
	return 0
}

var File_protos_emis_emis_proto protoreflect.FileDescriptor

var file_protos_emis_emis_proto_rawDesc = []byte{
	0x0a, 0x16, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x65, 0x6d, 0x69, 0x73, 0x2f, 0x65, 0x6d,
	0x69, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xa4, 0x02, 0x0a, 0x07, 0x45, 0x6d, 0x69, 0x73, 0x69, 0x6f,
	0x6e, 0x12, 0x16, 0x0a, 0x06, 0x63, 0x6f, 0x64, 0x69, 0x67, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x63, 0x6f, 0x64, 0x69, 0x67, 0x6f, 0x12, 0x1c, 0x0a, 0x09, 0x6f, 0x72, 0x67,
	0x61, 0x6e, 0x69, 0x73, 0x6d, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6f, 0x72,
	0x67, 0x61, 0x6e, 0x69, 0x73, 0x6d, 0x6f, 0x12, 0x29, 0x0a, 0x10, 0x74, 0x6f, 0x74, 0x61, 0x6c,
	0x5f, 0x64, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x6f, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x0f, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x44, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74,
	0x6f, 0x73, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x63, 0x69, 0x6f,
	0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70,
	0x63, 0x69, 0x6f, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x66, 0x69, 0x72, 0x6d, 0x61, 0x72, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x66, 0x69, 0x72, 0x6d, 0x61, 0x72, 0x12, 0x21, 0x0a, 0x0c,
	0x73, 0x65, 0x6c, 0x6c, 0x6f, 0x5f, 0x74, 0x69, 0x65, 0x6d, 0x70, 0x6f, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x0b, 0x73, 0x65, 0x6c, 0x6c, 0x6f, 0x54, 0x69, 0x65, 0x6d, 0x70, 0x6f, 0x12,
	0x1c, 0x0a, 0x09, 0x6e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x72, 0x18, 0x07, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x09, 0x6e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x72, 0x12, 0x16, 0x0a,
	0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x25, 0x0a, 0x0e, 0x74, 0x61, 0x6d, 0x61, 0x6e, 0x69, 0x6f,
	0x5f, 0x62, 0x6c, 0x6f, 0x71, 0x75, 0x65, 0x18, 0x09, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0d, 0x74,
	0x61, 0x6d, 0x61, 0x6e, 0x69, 0x6f, 0x42, 0x6c, 0x6f, 0x71, 0x75, 0x65, 0x22, 0xb6, 0x02, 0x0a,
	0x06, 0x52, 0x65, 0x63, 0x69, 0x62, 0x6f, 0x12, 0x1f, 0x0a, 0x0b, 0x63, 0x6f, 0x64, 0x5f, 0x65,
	0x6d, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x63, 0x6f,
	0x64, 0x45, 0x6d, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x1b, 0x0a, 0x09, 0x6e, 0x75, 0x6d, 0x5f,
	0x6f, 0x72, 0x64, 0x65, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x6e, 0x75, 0x6d,
	0x4f, 0x72, 0x64, 0x65, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x6e, 0x6f, 0x6d, 0x62, 0x72, 0x65, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6e, 0x6f, 0x6d, 0x62, 0x72, 0x65, 0x12, 0x1c, 0x0a,
	0x09, 0x61, 0x70, 0x65, 0x6c, 0x6c, 0x69, 0x64, 0x6f, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x09, 0x61, 0x70, 0x65, 0x6c, 0x6c, 0x69, 0x64, 0x6f, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x63,
	0x6f, 0x6e, 0x63, 0x65, 0x70, 0x74, 0x6f, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63,
	0x6f, 0x6e, 0x63, 0x65, 0x70, 0x74, 0x6f, 0x12, 0x18, 0x0a, 0x07, 0x69, 0x6d, 0x70, 0x6f, 0x72,
	0x74, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x69, 0x6d, 0x70, 0x6f, 0x72, 0x74,
	0x65, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x12, 0x1a, 0x0a, 0x08, 0x74, 0x65, 0x6c, 0x65, 0x66,
	0x6f, 0x6e, 0x6f, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x74, 0x65, 0x6c, 0x65, 0x66,
	0x6f, 0x6e, 0x6f, 0x12, 0x24, 0x0a, 0x0d, 0x6f, 0x62, 0x73, 0x65, 0x72, 0x76, 0x61, 0x63, 0x69,
	0x6f, 0x6e, 0x65, 0x73, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x6f, 0x62, 0x73, 0x65,
	0x72, 0x76, 0x61, 0x63, 0x69, 0x6f, 0x6e, 0x65, 0x73, 0x12, 0x10, 0x0a, 0x03, 0x70, 0x64, 0x66,
	0x18, 0x0a, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x70, 0x64, 0x66, 0x12, 0x18, 0x0a, 0x07, 0x74,
	0x61, 0x6d, 0x61, 0x6e, 0x69, 0x6f, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x74, 0x61,
	0x6d, 0x61, 0x6e, 0x69, 0x6f, 0x22, 0x1f, 0x0a, 0x0b, 0x50, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x22, 0x24, 0x0a, 0x0c, 0x50, 0x69, 0x6e, 0x67, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x72, 0x65, 0x70, 0x6c, 0x79, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x72, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x2b, 0x0a, 0x11,
	0x47, 0x65, 0x74, 0x45, 0x6d, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x16, 0x0a, 0x06, 0x63, 0x6f, 0x64, 0x69, 0x67, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x63, 0x6f, 0x64, 0x69, 0x67, 0x6f, 0x22, 0x38, 0x0a, 0x12, 0x47, 0x65, 0x74,
	0x45, 0x6d, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x22, 0x0a, 0x07, 0x65, 0x6d, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x08, 0x2e, 0x45, 0x6d, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x07, 0x65, 0x6d, 0x69, 0x73,
	0x69, 0x6f, 0x6e, 0x22, 0x15, 0x0a, 0x13, 0x47, 0x65, 0x74, 0x45, 0x6d, 0x69, 0x73, 0x69, 0x6f,
	0x6e, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x3e, 0x0a, 0x14, 0x47, 0x65,
	0x74, 0x45, 0x6d, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x26, 0x0a, 0x09, 0x65, 0x6d, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x65, 0x73, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x45, 0x6d, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x52,
	0x09, 0x65, 0x6d, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x65, 0x73, 0x22, 0x37, 0x0a, 0x11, 0x41, 0x64,
	0x64, 0x45, 0x6d, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x22, 0x0a, 0x07, 0x65, 0x6d, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x08, 0x2e, 0x45, 0x6d, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x07, 0x65, 0x6d, 0x69, 0x73,
	0x69, 0x6f, 0x6e, 0x22, 0x38, 0x0a, 0x12, 0x41, 0x64, 0x64, 0x45, 0x6d, 0x69, 0x73, 0x69, 0x6f,
	0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x22, 0x0a, 0x07, 0x65, 0x6d, 0x69,
	0x73, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x45, 0x6d, 0x69,
	0x73, 0x69, 0x6f, 0x6e, 0x52, 0x07, 0x65, 0x6d, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x22, 0x2e, 0x0a,
	0x14, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x45, 0x6d, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x63, 0x6f, 0x64, 0x69, 0x67, 0x6f, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x63, 0x6f, 0x64, 0x69, 0x67, 0x6f, 0x22, 0x45, 0x0a,
	0x15, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x45, 0x6d, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x14,
	0x0a, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x74,
	0x6f, 0x74, 0x61, 0x6c, 0x22, 0x2c, 0x0a, 0x12, 0x46, 0x61, 0x6b, 0x65, 0x45, 0x6d, 0x69, 0x73,
	0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x63, 0x6f,
	0x64, 0x69, 0x67, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x63, 0x6f, 0x64, 0x69,
	0x67, 0x6f, 0x22, 0x2b, 0x0a, 0x13, 0x46, 0x61, 0x6b, 0x65, 0x45, 0x6d, 0x69, 0x73, 0x69, 0x6f,
	0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x74,
	0x61, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x22,
	0x2c, 0x0a, 0x12, 0x49, 0x6e, 0x69, 0x74, 0x45, 0x6d, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x63, 0x6f, 0x64, 0x69, 0x67, 0x6f, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x63, 0x6f, 0x64, 0x69, 0x67, 0x6f, 0x22, 0x15, 0x0a,
	0x13, 0x49, 0x6e, 0x69, 0x74, 0x45, 0x6d, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x7d, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x52, 0x65, 0x63, 0x69, 0x62,
	0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x25, 0x0a, 0x0e, 0x63, 0x6f, 0x64, 0x69,
	0x67, 0x6f, 0x5f, 0x65, 0x6d, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0d, 0x63, 0x6f, 0x64, 0x69, 0x67, 0x6f, 0x45, 0x6d, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x12,
	0x21, 0x0a, 0x0c, 0x6e, 0x75, 0x6d, 0x65, 0x72, 0x6f, 0x5f, 0x6f, 0x72, 0x64, 0x65, 0x6e, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0b, 0x6e, 0x75, 0x6d, 0x65, 0x72, 0x6f, 0x4f, 0x72, 0x64,
	0x65, 0x6e, 0x12, 0x1f, 0x0a, 0x0b, 0x69, 0x6e, 0x63, 0x6c, 0x75, 0x69, 0x72, 0x5f, 0x70, 0x64,
	0x66, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0a, 0x69, 0x6e, 0x63, 0x6c, 0x75, 0x69, 0x72,
	0x50, 0x64, 0x66, 0x22, 0x34, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x52, 0x65, 0x63, 0x69, 0x62, 0x6f,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1f, 0x0a, 0x06, 0x72, 0x65, 0x63, 0x69,
	0x62, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x07, 0x2e, 0x52, 0x65, 0x63, 0x69, 0x62,
	0x6f, 0x52, 0x06, 0x72, 0x65, 0x63, 0x69, 0x62, 0x6f, 0x22, 0x52, 0x0a, 0x11, 0x47, 0x65, 0x74,
	0x52, 0x65, 0x63, 0x69, 0x62, 0x6f, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x25,
	0x0a, 0x0e, 0x63, 0x6f, 0x64, 0x69, 0x67, 0x6f, 0x5f, 0x65, 0x6d, 0x69, 0x73, 0x69, 0x6f, 0x6e,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x63, 0x6f, 0x64, 0x69, 0x67, 0x6f, 0x45, 0x6d,
	0x69, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x62, 0x6c, 0x6f, 0x71, 0x75, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x62, 0x6c, 0x6f, 0x71, 0x75, 0x65, 0x22, 0x37, 0x0a,
	0x12, 0x47, 0x65, 0x74, 0x52, 0x65, 0x63, 0x69, 0x62, 0x6f, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x21, 0x0a, 0x07, 0x72, 0x65, 0x63, 0x69, 0x62, 0x6f, 0x73, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x07, 0x2e, 0x52, 0x65, 0x63, 0x69, 0x62, 0x6f, 0x52, 0x07, 0x72,
	0x65, 0x63, 0x69, 0x62, 0x6f, 0x73, 0x22, 0x33, 0x0a, 0x10, 0x41, 0x64, 0x64, 0x52, 0x65, 0x63,
	0x69, 0x62, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1f, 0x0a, 0x06, 0x72, 0x65,
	0x63, 0x69, 0x62, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x07, 0x2e, 0x52, 0x65, 0x63,
	0x69, 0x62, 0x6f, 0x52, 0x06, 0x72, 0x65, 0x63, 0x69, 0x62, 0x6f, 0x22, 0x34, 0x0a, 0x11, 0x41,
	0x64, 0x64, 0x52, 0x65, 0x63, 0x69, 0x62, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x1f, 0x0a, 0x06, 0x72, 0x65, 0x63, 0x69, 0x62, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x07, 0x2e, 0x52, 0x65, 0x63, 0x69, 0x62, 0x6f, 0x52, 0x06, 0x72, 0x65, 0x63, 0x69, 0x62,
	0x6f, 0x22, 0x5f, 0x0a, 0x13, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x63, 0x69, 0x62,
	0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x25, 0x0a, 0x0e, 0x63, 0x6f, 0x64, 0x69,
	0x67, 0x6f, 0x5f, 0x65, 0x6d, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0d, 0x63, 0x6f, 0x64, 0x69, 0x67, 0x6f, 0x45, 0x6d, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x12,
	0x21, 0x0a, 0x0c, 0x6e, 0x75, 0x6d, 0x65, 0x72, 0x6f, 0x5f, 0x6f, 0x72, 0x64, 0x65, 0x6e, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0b, 0x6e, 0x75, 0x6d, 0x65, 0x72, 0x6f, 0x4f, 0x72, 0x64,
	0x65, 0x6e, 0x22, 0x44, 0x0a, 0x14, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x63, 0x69,
	0x62, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x22, 0x74, 0x0a, 0x16, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x50, 0x64, 0x66, 0x52, 0x65, 0x63, 0x69, 0x62, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x25, 0x0a, 0x0e, 0x63, 0x6f, 0x64, 0x69, 0x67, 0x6f, 0x5f, 0x65, 0x6d, 0x69,
	0x73, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x63, 0x6f, 0x64, 0x69,
	0x67, 0x6f, 0x45, 0x6d, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x21, 0x0a, 0x0c, 0x6e, 0x75, 0x6d,
	0x65, 0x72, 0x6f, 0x5f, 0x6f, 0x72, 0x64, 0x65, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x0b, 0x6e, 0x75, 0x6d, 0x65, 0x72, 0x6f, 0x4f, 0x72, 0x64, 0x65, 0x6e, 0x12, 0x10, 0x0a, 0x03,
	0x70, 0x64, 0x66, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x70, 0x64, 0x66, 0x22, 0x33,
	0x0a, 0x17, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x50, 0x64, 0x66, 0x52, 0x65, 0x63, 0x69, 0x62,
	0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x74, 0x61, 0x6d,
	0x61, 0x6e, 0x69, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x74, 0x61, 0x6d, 0x61,
	0x6e, 0x69, 0x6f, 0x32, 0xec, 0x05, 0x0a, 0x0b, 0x45, 0x6d, 0x69, 0x73, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x12, 0x23, 0x0a, 0x04, 0x50, 0x69, 0x6e, 0x67, 0x12, 0x0c, 0x2e, 0x50, 0x69,
	0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0d, 0x2e, 0x50, 0x69, 0x6e, 0x67,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x37, 0x0a, 0x05, 0x52, 0x65, 0x73, 0x65,
	0x74, 0x12, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74,
	0x79, 0x12, 0x35, 0x0a, 0x0a, 0x47, 0x65, 0x74, 0x45, 0x6d, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x12,
	0x12, 0x2e, 0x47, 0x65, 0x74, 0x45, 0x6d, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x13, 0x2e, 0x47, 0x65, 0x74, 0x45, 0x6d, 0x69, 0x73, 0x69, 0x6f, 0x6e,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3b, 0x0a, 0x0c, 0x47, 0x65, 0x74, 0x45,
	0x6d, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x65, 0x73, 0x12, 0x14, 0x2e, 0x47, 0x65, 0x74, 0x45, 0x6d,
	0x69, 0x73, 0x69, 0x6f, 0x6e, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x15,
	0x2e, 0x47, 0x65, 0x74, 0x45, 0x6d, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x65, 0x73, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x35, 0x0a, 0x0a, 0x41, 0x64, 0x64, 0x45, 0x6d, 0x69, 0x73,
	0x69, 0x6f, 0x6e, 0x12, 0x12, 0x2e, 0x41, 0x64, 0x64, 0x45, 0x6d, 0x69, 0x73, 0x69, 0x6f, 0x6e,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x13, 0x2e, 0x41, 0x64, 0x64, 0x45, 0x6d, 0x69,
	0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3e, 0x0a, 0x0d,
	0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x45, 0x6d, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x15, 0x2e,
	0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x45, 0x6d, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x45, 0x6d, 0x69,
	0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x38, 0x0a, 0x0b,
	0x46, 0x61, 0x6b, 0x65, 0x45, 0x6d, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x13, 0x2e, 0x46, 0x61,
	0x6b, 0x65, 0x45, 0x6d, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x14, 0x2e, 0x46, 0x61, 0x6b, 0x65, 0x45, 0x6d, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x38, 0x0a, 0x0b, 0x49, 0x6e, 0x69, 0x74, 0x45, 0x6d,
	0x69, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x13, 0x2e, 0x49, 0x6e, 0x69, 0x74, 0x45, 0x6d, 0x69, 0x73,
	0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x14, 0x2e, 0x49, 0x6e, 0x69,
	0x74, 0x45, 0x6d, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x32, 0x0a, 0x09, 0x47, 0x65, 0x74, 0x52, 0x65, 0x63, 0x69, 0x62, 0x6f, 0x12, 0x11, 0x2e,
	0x47, 0x65, 0x74, 0x52, 0x65, 0x63, 0x69, 0x62, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x12, 0x2e, 0x47, 0x65, 0x74, 0x52, 0x65, 0x63, 0x69, 0x62, 0x6f, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x35, 0x0a, 0x0a, 0x47, 0x65, 0x74, 0x52, 0x65, 0x63, 0x69, 0x62,
	0x6f, 0x73, 0x12, 0x12, 0x2e, 0x47, 0x65, 0x74, 0x52, 0x65, 0x63, 0x69, 0x62, 0x6f, 0x73, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x13, 0x2e, 0x47, 0x65, 0x74, 0x52, 0x65, 0x63, 0x69,
	0x62, 0x6f, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x32, 0x0a, 0x09, 0x41,
	0x64, 0x64, 0x52, 0x65, 0x63, 0x69, 0x62, 0x6f, 0x12, 0x11, 0x2e, 0x41, 0x64, 0x64, 0x52, 0x65,
	0x63, 0x69, 0x62, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x12, 0x2e, 0x41, 0x64,
	0x64, 0x52, 0x65, 0x63, 0x69, 0x62, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x3b, 0x0a, 0x0c, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x63, 0x69, 0x62, 0x6f, 0x12,
	0x14, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x63, 0x69, 0x62, 0x6f, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x15, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65,
	0x63, 0x69, 0x62, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x44, 0x0a, 0x0f,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x50, 0x64, 0x66, 0x52, 0x65, 0x63, 0x69, 0x62, 0x6f, 0x12,
	0x17, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x50, 0x64, 0x66, 0x52, 0x65, 0x63, 0x69, 0x62,
	0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x50, 0x64, 0x66, 0x52, 0x65, 0x63, 0x69, 0x62, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x42, 0x08, 0x5a, 0x06, 0x2e, 0x2f, 0x65, 0x6d, 0x69, 0x73, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protos_emis_emis_proto_rawDescOnce sync.Once
	file_protos_emis_emis_proto_rawDescData = file_protos_emis_emis_proto_rawDesc
)

func file_protos_emis_emis_proto_rawDescGZIP() []byte {
	file_protos_emis_emis_proto_rawDescOnce.Do(func() {
		file_protos_emis_emis_proto_rawDescData = protoimpl.X.CompressGZIP(file_protos_emis_emis_proto_rawDescData)
	})
	return file_protos_emis_emis_proto_rawDescData
}

var file_protos_emis_emis_proto_msgTypes = make([]protoimpl.MessageInfo, 26)
var file_protos_emis_emis_proto_goTypes = []interface{}{
	(*Emision)(nil),                 // 0: Emision
	(*Recibo)(nil),                  // 1: Recibo
	(*PingRequest)(nil),             // 2: PingRequest
	(*PingResponse)(nil),            // 3: PingResponse
	(*GetEmisionRequest)(nil),       // 4: GetEmisionRequest
	(*GetEmisionResponse)(nil),      // 5: GetEmisionResponse
	(*GetEmisionesRequest)(nil),     // 6: GetEmisionesRequest
	(*GetEmisionesResponse)(nil),    // 7: GetEmisionesResponse
	(*AddEmisionRequest)(nil),       // 8: AddEmisionRequest
	(*AddEmisionResponse)(nil),      // 9: AddEmisionResponse
	(*DeleteEmisionRequest)(nil),    // 10: DeleteEmisionRequest
	(*DeleteEmisionResponse)(nil),   // 11: DeleteEmisionResponse
	(*FakeEmisionRequest)(nil),      // 12: FakeEmisionRequest
	(*FakeEmisionResponse)(nil),     // 13: FakeEmisionResponse
	(*InitEmisionRequest)(nil),      // 14: InitEmisionRequest
	(*InitEmisionResponse)(nil),     // 15: InitEmisionResponse
	(*GetReciboRequest)(nil),        // 16: GetReciboRequest
	(*GetReciboResponse)(nil),       // 17: GetReciboResponse
	(*GetRecibosRequest)(nil),       // 18: GetRecibosRequest
	(*GetRecibosResponse)(nil),      // 19: GetRecibosResponse
	(*AddReciboRequest)(nil),        // 20: AddReciboRequest
	(*AddReciboResponse)(nil),       // 21: AddReciboResponse
	(*DeleteReciboRequest)(nil),     // 22: DeleteReciboRequest
	(*DeleteReciboResponse)(nil),    // 23: DeleteReciboResponse
	(*UpdatePdfReciboRequest)(nil),  // 24: UpdatePdfReciboRequest
	(*UpdatePdfReciboResponse)(nil), // 25: UpdatePdfReciboResponse
	(*empty.Empty)(nil),             // 26: google.protobuf.Empty
}
var file_protos_emis_emis_proto_depIdxs = []int32{
	0,  // 0: GetEmisionResponse.emision:type_name -> Emision
	0,  // 1: GetEmisionesResponse.emisiones:type_name -> Emision
	0,  // 2: AddEmisionRequest.emision:type_name -> Emision
	0,  // 3: AddEmisionResponse.emision:type_name -> Emision
	1,  // 4: GetReciboResponse.recibo:type_name -> Recibo
	1,  // 5: GetRecibosResponse.recibos:type_name -> Recibo
	1,  // 6: AddReciboRequest.recibo:type_name -> Recibo
	1,  // 7: AddReciboResponse.recibo:type_name -> Recibo
	2,  // 8: EmisService.Ping:input_type -> PingRequest
	26, // 9: EmisService.Reset:input_type -> google.protobuf.Empty
	4,  // 10: EmisService.GetEmision:input_type -> GetEmisionRequest
	6,  // 11: EmisService.GetEmisiones:input_type -> GetEmisionesRequest
	8,  // 12: EmisService.AddEmision:input_type -> AddEmisionRequest
	10, // 13: EmisService.DeleteEmision:input_type -> DeleteEmisionRequest
	12, // 14: EmisService.FakeEmision:input_type -> FakeEmisionRequest
	14, // 15: EmisService.InitEmision:input_type -> InitEmisionRequest
	16, // 16: EmisService.GetRecibo:input_type -> GetReciboRequest
	18, // 17: EmisService.GetRecibos:input_type -> GetRecibosRequest
	20, // 18: EmisService.AddRecibo:input_type -> AddReciboRequest
	22, // 19: EmisService.DeleteRecibo:input_type -> DeleteReciboRequest
	24, // 20: EmisService.UpdatePdfRecibo:input_type -> UpdatePdfReciboRequest
	3,  // 21: EmisService.Ping:output_type -> PingResponse
	26, // 22: EmisService.Reset:output_type -> google.protobuf.Empty
	5,  // 23: EmisService.GetEmision:output_type -> GetEmisionResponse
	7,  // 24: EmisService.GetEmisiones:output_type -> GetEmisionesResponse
	9,  // 25: EmisService.AddEmision:output_type -> AddEmisionResponse
	11, // 26: EmisService.DeleteEmision:output_type -> DeleteEmisionResponse
	13, // 27: EmisService.FakeEmision:output_type -> FakeEmisionResponse
	15, // 28: EmisService.InitEmision:output_type -> InitEmisionResponse
	17, // 29: EmisService.GetRecibo:output_type -> GetReciboResponse
	19, // 30: EmisService.GetRecibos:output_type -> GetRecibosResponse
	21, // 31: EmisService.AddRecibo:output_type -> AddReciboResponse
	23, // 32: EmisService.DeleteRecibo:output_type -> DeleteReciboResponse
	25, // 33: EmisService.UpdatePdfRecibo:output_type -> UpdatePdfReciboResponse
	21, // [21:34] is the sub-list for method output_type
	8,  // [8:21] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_protos_emis_emis_proto_init() }
func file_protos_emis_emis_proto_init() {
	if File_protos_emis_emis_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protos_emis_emis_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Emision); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_emis_emis_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Recibo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_emis_emis_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PingRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_emis_emis_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PingResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_emis_emis_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetEmisionRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_emis_emis_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetEmisionResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_emis_emis_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetEmisionesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_emis_emis_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetEmisionesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_emis_emis_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddEmisionRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_emis_emis_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddEmisionResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_emis_emis_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteEmisionRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_emis_emis_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteEmisionResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_emis_emis_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FakeEmisionRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_emis_emis_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FakeEmisionResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_emis_emis_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InitEmisionRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_emis_emis_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InitEmisionResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_emis_emis_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetReciboRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_emis_emis_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetReciboResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_emis_emis_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetRecibosRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_emis_emis_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetRecibosResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_emis_emis_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddReciboRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_emis_emis_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddReciboResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_emis_emis_proto_msgTypes[22].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteReciboRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_emis_emis_proto_msgTypes[23].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteReciboResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_emis_emis_proto_msgTypes[24].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdatePdfReciboRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_emis_emis_proto_msgTypes[25].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdatePdfReciboResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protos_emis_emis_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   26,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protos_emis_emis_proto_goTypes,
		DependencyIndexes: file_protos_emis_emis_proto_depIdxs,
		MessageInfos:      file_protos_emis_emis_proto_msgTypes,
	}.Build()
	File_protos_emis_emis_proto = out.File
	file_protos_emis_emis_proto_rawDesc = nil
	file_protos_emis_emis_proto_goTypes = nil
	file_protos_emis_emis_proto_depIdxs = nil
}
